### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by lnicola**
This made me chuckle :smiley:.

### CODE REVIEW

**Comment by unic0rn9k** [comment]
This is my first time getting a pr. Thank you very much for the help!

**Comment by unic0rn9k** [comment]
Just noticed the typo was only fixed in the readme.

Changes to the readme should be added to the documentation in the top of `src/lib.rs` and then `cargo-readme --no-title` should be used to generate the readme from the docs.

Any help making it easier to contribute or clearifying confusing things like this would be great, as I'm still very new to opensource and git. Thanks again for your time.

**Comment by lnicola** [comment]
Ah, sorry, I'll send a PR to fix it properly later.

**Comment by unic0rn9k** [comment]
Thanks!

**Pull request merged**
